alias vzshrc="vim ~/.zshrc"
alias szshrc="source ~/.zshrc"
alias bi="brew install"
alias bic="bi --cask"
alias python="python3"
alias py="python"
alias mci="mvn clean install"
alias mcp="mvn clean package"
alias mcd="mvn clean deploy"
alias mcpst="mcp -DskipTests=true -Dmaven.test.skip=true"
alias grps="git rev-parse --short"
alias gcamc="git commit --amend -C @"
alias java-debug="java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000"
alias get-local-ip="ifconfig| grep 'inet ' | grep '10.' | awk '{print \$2}'"
